### ISSUE TITLE
[Concern] Crystal graph

### ISSUE THREAD

**Issue by yanxon** [qzhu2017/PyXtal_ml#40]
@qzhu2017 

https://github.com/qzhu2017/PyXtal_ml/blob/b11b3405996b4e587ab014e9727239f59440a042/pyxtal_ml/descriptors/crystal_graph_QZ.py#L68

I just read your comments in the code.

I think the GaussianDistance is the secret sauce of crystal graph. Without GaussianDistance, nbr_fea is just distances between two atoms without the mapping.

**Comment by yanxon** [comment]
@qzhu2017 

Also, let me work on the code.

Thank you,

Howard

**Comment by qzhu2017** [comment]
Just to clarify, the learning of images and graphs should be very different.


@yanxon The way which we understand CNN is used for image processing.
Graphs is very different from 2D images, as we care more about the nodes, edges, and weight. These things can create a lot of discontinuity if we treat them as a 2D image. So a lot of methods have been developed by the community, the real name is called `Graph Convolutional Networks (GCN)`. 
The crystal graph should belong to `GCN` problem instead of `CNN`.

**Comment by qzhu2017** [comment]
http://tkipf.github.io/graph-convolutional-networks/

**Comment by yanxon** [comment]
I see. Thank you for the info. I will work on this and the gaussian descriptor. Hopefully, I can get them done by Monday.
