### ISSUE TITLE
github page for pyxtal_ml

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/PyXtal_ml#44]
Can any of your create a github page for the documentation of PyXtal_ml?

@David-Zagaceta 
@yanxon

**Comment by yanxon** [comment]
@qzhu2017 @David-Zagaceta 

We don't have access to the setting of this repo because this repo is owned by you.

But, you can easily make GitHub host the doc by:
1. Go to the settings in this repo.
2. Under the GitHub Pages, choose enable the source. I believe you choose "master branch / doc folder."

Please let me know if it doesn't work.

**Comment by qzhu2017** [comment]
@yanxon 
I have figured out a way to synchronize the documentation via the read doc.
https://pyxtal-ml.readthedocs.io/en/latest/

Let's work on the documentation later on.
