### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/PyXtal_ml#7]
@yanxon 

I notice a couple of issues in `sp_metal_aflow_844.json`

1, It has a lot of entries which return None in 'form_energy_cell'
2, It would be good to normalize the values when you create the json files. This applies to those extensive properties.

For instance, 
DOS: should be always /A^3
Formation energy: should be always /atom.

**Comment by yanxon** [comment]
1. Yes. I notice that not all of the sp_metal_aflow_844.json has the form_energy_cell. It maybe due to the information isn't available from AFLOW itself.

2. I have the value readily to be normalized (like volume and n_atoms). I thought it's better if they're separate. It's probably the best if they're normalized at the beginning. 

3. Also, I just posted ML.py. I will integrate your code with mine.

**Comment by qzhu2017** [comment]
@yanxon I have added another set from Jarvis.
jarvis_25923.json

**Comment by qzhu2017** [comment]
@yanxon Let's set the rule for the creation of json file. I have placed my scripts to convert the data from jarvis and materials project in https://github.com/qzhu2017/ML-Materials/tree/master/datasets/scripts

Please follow the same convention, if you want to include materials from other database.

**Comment by qzhu2017** [comment]
I have include this description in READ.ME
